services:
  habittrove:
    ports:
      - "3000:3000"
    volumes:
      - "./data:/app/data" # Use a relative path instead of $(pwd)
    image: dohsimpson/habittrove
    environment:
      - AUTH_SECRET=your-secret-key-here
