services:
  habittrove:
    ports:
      - "3000:3000"
    volumes:
      - "./data:/app/data"
      - "./backups:/app/backups"
    image: dohsimpson/habittrove
    environment:
      - AUTH_SECRET=your-secret-key-here # Replace with your actual secret
